---

name: Checks
 
on: [push]
 
jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py test"
        # This step runs the tests in the application
        # It uses the `docker compose run` command to run the tests in the app service
        # The `--rm` flag removes the container after the command is executed
        # The `sh -c` command is used to run the `python manage.py test
      - name: Lint
        run: docker compose run --rm app sh -c "flake8"